name: CI

on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest

    #container: mmgeorge/sbcl-debian:1.4.2

    steps:
    #- uses: actions/checkout@v2
    - name: Checkout
      run: |
        git clone https://github.com/mmgeorge/sly-asdf ~/common-lisp/sly-asdf --depth 1
        git clone https://github.com/joaotavora/sly ~/common-lisp/sly --depth 1
    - name: Load package
      run: sbcl --eval '(asdf:load-system "slynk-asdf")' --non-interactive | tee log.txt
