name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Checkout repo
      run: git clone https://github.com/mmgeorge/sly-asdf ~/common-lisp/sly-asdf --depth 1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
